import { OrnamentDivider, HeartSigilIcon } from '@/components/icons/SvgIcons';
import { usePageMeta } from '@/hooks/usePageMeta';

interface PolicyPageProps {
  kind: 'privacy' | 'cookies';
  onBack: () => void;
}

const PRIVACY_SECTIONS = [
  {
    title: 'Scope',
    body: 'This policy explains what this service stores and observes when someone writes, opens, unlocks, manages, or requests the removal of a letter.',
  },
  {
    title: 'Information you provide',
    body: 'The service stores the letter content, recipient name, design choices, optional date line, decorative settings, optional passphrase protection, and related management metadata needed to deliver and maintain the letter.',
  },
  {
    title: 'Operational request data',
    body: 'To protect the service and help review support or deletion requests in the absence of accounts, the service may record hashed network identifiers, browser agent, language headers, referrer, do-not-track signal, and first-party browser or session references generated by the site itself.',
  },
  {
    title: 'Client-side environment data',
    body: 'The service may also record non-permissioned environment details such as timezone, screen and viewport size, device pixel ratio, preferred color scheme, reduced-motion preference, touch capability, processor concurrency, approximate device memory, and storage availability. These are used for abuse review, service diagnostics, and continuity checks when someone later asks for a letter to be deleted.',
  },
  {
    title: 'What is not requested',
    body: 'The normal experience does not ask for camera, microphone, contact list, or precise location access. If those capabilities are ever added later, they should be requested separately and documented before release.',
  },
  {
    title: 'Purpose of processing',
    body: 'Data is used to deliver letters, apply design settings, secure private letters, support authors, review abuse, compare deletion requests against prior usage patterns, and operate the service safely in production.',
  },
  {
    title: 'Retention',
    body: 'Letters remain available until they are deleted, expired, or otherwise removed by the operator. Operational caches, logs, and event traces should be retained only as long as they are genuinely needed for support, abuse prevention, backup, and maintenance.',
  },
  {
    title: 'Disclosure',
    body: 'This version is designed for first-party operation. If third-party analytics, external support tools, payment services, or email providers are added later, this policy should be updated to reflect those processors and the reasons they receive data.',
  },
  {
    title: 'Operator responsibility',
    body: 'Before public launch, the operator should add a real contact point for privacy or deletion requests, confirm regional legal requirements, and review backup, log, and access controls in the hosting environment.',
  },
];

const COOKIE_SECTIONS = [
  {
    title: 'What is used',
    body: 'This service uses first-party browser storage such as localStorage and sessionStorage. These are used for management tokens, draft recovery, browser references, session references, and other essential state that allows the experience to work without a login system.',
  },
  {
    title: 'Essential functions',
    body: 'These first-party values help writers return to drafts, preview and manage their own letters, and help the operator compare support or deletion requests against earlier first-party usage traces.',
  },
  {
    title: 'No advertising cookies by default',
    body: 'This version is not built around adtech, behavioral advertising, or third-party marketing cookies by default.',
  },
  {
    title: 'Future additions',
    body: 'If analytics, chat widgets, embedded media, A/B tools, CDN-managed cookies, or third-party scripts are introduced later, this policy should be updated before deployment so visitors can be told what changes.',
  },
  {
    title: 'Storage duration',
    body: 'Some browser values persist until cleared by the visitor or overwritten by the service. Session-scoped values typically end when the browser session ends, while longer-lived local values may remain until manually removed.',
  },
];

export default function PolicyPage({ kind, onBack }: PolicyPageProps) {
  const title = kind === 'privacy' ? 'Privacy' : 'Cookie';
  const sections = kind === 'privacy' ? PRIVACY_SECTIONS : COOKIE_SECTIONS;
  usePageMeta({
    title: `${title} Policy — Courier of Hearts`,
    description: kind === 'privacy'
      ? 'Read how Courier of Hearts stores letters, first-party traces, and essential operational data.'
      : 'Read how Courier of Hearts uses first-party browser storage and essential cookie-like state.',
    robots: 'index,follow',
  });

  return (
    <div className="min-h-screen parchment-bg">
      <nav className="flex items-center justify-between px-4 py-3 md:px-8 md:py-4" style={{ borderBottom: '1px solid rgba(139,115,64,0.1)' }}>
        <button onClick={onBack} className="font-heading text-[11px] tracking-[0.12em] text-ink/50 uppercase hover:text-ink/80 transition-colors duration-500">&larr; Home</button>
        <div className="flex items-center gap-2">
          <HeartSigilIcon size={18} color="#6B1025" />
          <span className="font-heading text-[10px] tracking-[0.2em] text-ink/55 uppercase hidden md:inline">{title} Policy</span>
        </div>
        <div className="w-16" />
      </nav>

      <div className="max-w-3xl mx-auto px-4 py-8 md:py-12 relative z-10">
        <header className="text-center mb-8">
          <h1 className="font-display text-3xl md:text-4xl text-ink/88 mb-2">{title} Policy</h1>
          <p className="font-body text-[15px] md:text-[16px] text-ink/56 italic">Written plainly, so visitors are not left guessing.</p>
          <OrnamentDivider className="w-44 mx-auto mt-5" color="#8b7340" />
        </header>

        <article className="letter-paper rounded-sm px-5 py-6 md:px-8 md:py-9 space-y-6">
          <p className="font-body text-[15px] text-ink/68 leading-[1.9]">
            This service is designed to feel personal without forcing account creation. Because of that choice, certain first-party operational records are used to preserve letters, protect the service, and responsibly review support or removal requests.
          </p>

          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="font-heading text-[11px] tracking-[0.18em] uppercase text-ink/64 mb-2">{section.title}</h2>
              <p className="font-body text-[15px] text-ink/66 leading-[1.85]">{section.body}</p>
            </section>
          ))}
        </article>
      </div>
    </div>
  );
}
